### ISSUE TITLE
3.x - Sensors are not updated when other user is logged in

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#81] opened 2022-11-15 08:45 UTC
My ID.4 got updated to 3.0 (First OTA wave). One of the functions we were really happy to have are profiles.
Our mirrors, seats, colors and radio stations are now in sync with the person that's driving. 

Awesome. 

One big issue i now have with implementing the new 3.0 sensors into Home Asssistant is that the sensors are not updating when the other user is driving the car. Also when she parks the car, the car still holds her account so no sensors are updated. 

Is know this a privacy thing, do you think there is a way around this? State of charge is not that much of a secret. 
I do understand that parking position is private. 

The app is also greyed out when she uses it :)

**Comment by tillsteinbach** [comment] 2022-11-15 09:06
This is a known problem and you will experience the same with the official app. The problem is that the second user is a "guest user" and not a real "secondary user" hopefully this will be fixed soon by VW.

**Closed by tillsteinbach** 2022-11-15 09:06 UTC
Labels: enhancement
